apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stackstate-tls
  namespace: suse-observability
spec:
  secretName: stackstate-tls 
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer  
  dnsNames:
    - ${STACKSTATE_URL}  
