apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stackstate-tls
  namespace: suse-observability
spec:
  secretName: stackstate-tls  # Name of the secret to store the certificate
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer  # This assumes you're using Let's Encrypt. Update if different.
  dnsNames:
    - "stackstate.209.38.124.11.nip.io"  # The domain that needs the certificate
