apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stackstate-ingress
  namespace: suse-observability
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - stackstate.64.225.87.55.nip.io
    secretName: stackstate-tls
  rules:
  - host: stackstate.64.225.87.55.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: suse-observability-router
            port:
              number: 8080

